version: '3'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"  # Added port for API server
    volumes:
      - .:/app
      - ./exports:/app/exports
      - ./logs:/app/logs
      - ./database:/app/database
      - ./cache:/app/cache
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    container_name: chess-gender-inequality

  # Uncomment to enable a dashboard service
  # dashboard:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dashboard
  #   ports:
  #     - "8050:8050"
  #   volumes:
  #     - ./exports:/app/exports
  #     - ./database:/app/database
  #   depends_on:
  #     - jupyter
  #   restart: unless-stopped
  #   container_name: chess-gender-dashboard
